# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.widget.setObjectName("widget")
        self.startBtn = QtWidgets.QPushButton(self.widget)
        self.startBtn.setGeometry(QtCore.QRect(2, 1, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.shutdownBtn = QtWidgets.QPushButton(self.widget)
        self.shutdownBtn.setGeometry(QtCore.QRect(210, 0, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.shutdownBtn.setFont(font)
        self.shutdownBtn.setObjectName("shutdownBtn")
        self.restartBtn = QtWidgets.QPushButton(self.widget)
        self.restartBtn.setGeometry(QtCore.QRect(420, 0, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.restartBtn.setFont(font)
        self.restartBtn.setObjectName("restartBtn")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(230, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scanButton = QtWidgets.QPushButton(self.widget)
        self.scanButton.setGeometry(QtCore.QRect(20, 360, 601, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.scanButton.setFont(font)
        self.scanButton.setObjectName("scanButton")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(25, 161, 591, 191))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startBtn.setText(_translate("Form", "Start"))
        self.shutdownBtn.setText(_translate("Form", "Shutdown"))
        self.restartBtn.setText(_translate("Form", "Restart"))
        self.label.setText(_translate("Form", "Name Of Scan"))
        self.scanButton.setText(_translate("Form", "Scan"))
