# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/report.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.widget.setObjectName("widget")
        self.startBtn = QtWidgets.QPushButton(self.widget)
        self.startBtn.setGeometry(QtCore.QRect(2, 1, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.shutdownBtn = QtWidgets.QPushButton(self.widget)
        self.shutdownBtn.setGeometry(QtCore.QRect(210, 0, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.shutdownBtn.setFont(font)
        self.shutdownBtn.setObjectName("shutdownBtn")
        self.restartBtn = QtWidgets.QPushButton(self.widget)
        self.restartBtn.setGeometry(QtCore.QRect(420, 0, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.restartBtn.setFont(font)
        self.restartBtn.setObjectName("restartBtn")
        self.imgLabel = QtWidgets.QLabel(self.widget)
        self.imgLabel.setGeometry(QtCore.QRect(120, 130, 390, 300))
        self.imgLabel.setText("")
        self.imgLabel.setScaledContents(True)
        self.imgLabel.setObjectName("imgLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startBtn.setText(_translate("Form", "Start"))
        self.shutdownBtn.setText(_translate("Form", "Shutdown"))
        self.restartBtn.setText(_translate("Form", "Restart"))
