# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.widget.setObjectName("widget")
        self.startBtn = QtWidgets.QPushButton(self.widget)
        self.startBtn.setGeometry(QtCore.QRect(2, 1, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.shutdownBtn = QtWidgets.QPushButton(self.widget)
        self.shutdownBtn.setGeometry(QtCore.QRect(210, 0, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.shutdownBtn.setFont(font)
        self.shutdownBtn.setObjectName("shutdownBtn")
        self.restartBtn = QtWidgets.QPushButton(self.widget)
        self.restartBtn.setGeometry(QtCore.QRect(420, 0, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.restartBtn.setFont(font)
        self.restartBtn.setObjectName("restartBtn")
        self.lbtext = QtWidgets.QLabel(self.widget)
        self.lbtext.setGeometry(QtCore.QRect(80, 130, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbtext.setFont(font)
        self.lbtext.setAlignment(QtCore.Qt.AlignCenter)
        self.lbtext.setObjectName("lbtext")
        self.statusEdit = QtWidgets.QLineEdit(self.widget)
        self.statusEdit.setGeometry(QtCore.QRect(160, 190, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.statusEdit.setFont(font)
        self.statusEdit.setObjectName("statusEdit")
        self.reportBtn = QtWidgets.QPushButton(self.widget)
        self.reportBtn.setGeometry(QtCore.QRect(10, 360, 611, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.reportBtn.setFont(font)
        self.reportBtn.setObjectName("reportBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startBtn.setText(_translate("Form", "Start"))
        self.shutdownBtn.setText(_translate("Form", "Shutdown"))
        self.restartBtn.setText(_translate("Form", "Restart"))
        self.lbtext.setText(_translate("Form", "Status"))
        self.reportBtn.setText(_translate("Form", "Report"))
